version: "3.8"

services:
    postgres:
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_DB: pg
            POSTGRES_USER: pgmaster
            POSTGRES_PASSWORD: qwerty
            TZ: Europe/Moscow
        ports:
            - 172.17.0.1:5454:5432
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5
    migrate:
        image: migrate/migrate
        volumes:
            - ./migrations:/migrations
        command: ["-path", "migrations", "-database",  "postgres://pgmaster:qwerty@172.17.0.1:5454/pg?sslmode=disable", "up"]
        depends_on:
            postgres:
                condition: service_healthy
    rabbitmq:
        image: rabbitmq:latest
        restart: always
        ports:
            - 172.17.0.1:5672:5672
        healthcheck:
            test: rabbitmq-diagnostics -q ping
            interval: 30s
            timeout: 30s
            retries: 3    
    web:
        image: example/chat
        build: 
            dockerfile: Dockerfile.scratch
        ports:
            - 172.17.0.1:8001:8001
        network_mode: host
        depends_on:
            rabbitmq:
                condition: service_healthy
            postgres:
                condition: service_healthy 
    web2:
        image: example2/chat
        build: 
            dockerfile: Dockerfile2.scratch
        ports:
            - 172.17.0.1:8002:8002
        network_mode: host
        depends_on:
            rabbitmq:
                condition: service_healthy
            postgres:
                condition: service_healthy
    
    #pgadmin4:
    #    image: dpage/pgadmin4:latest
    #    restart: always
    #    environment:
    #        PGADMIN_DEFAULT_EMAIL: admin2@mail.ru
    #        PGADMIN_DEFAULT_PASSWORD: qwerty
    #        PGADMIN_LISTEN_PORT: 8080
    #    ports:
    #        - 172.17.0.1:8080:8080
    

            
